-- MySQL Script generated by MySQL Workbench
-- Wed Sep 11 23:24:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dis
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dis` ;

-- -----------------------------------------------------
-- Schema dis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dis` DEFAULT CHARACTER SET utf8 ;
USE `dis` ;

-- -----------------------------------------------------
-- Table `dis`.`bicikli`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dis`.`bicikli` ;

CREATE TABLE IF NOT EXISTS `dis`.`bicikli` (
  `ID_BICIKLI` INT(11) NOT NULL,
  `NAZIV` VARCHAR(45) NOT NULL,
  `CENA` VARCHAR(45) NOT NULL,
  `OPIS` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_BICIKLI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dis`.`email_verifikacija_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dis`.`email_verifikacija_status` ;

CREATE TABLE IF NOT EXISTS `dis`.`email_verifikacija_status` (
  `ID_EMAIL_VERIFIKACIJA_STATUS` INT(11) NOT NULL AUTO_INCREMENT,
  `NAZIV` VARCHAR(45) NOT NULL,
  `OPIS` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_EMAIL_VERIFIKACIJA_STATUS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dis`.`korisnik_rola`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dis`.`korisnik_rola` ;

CREATE TABLE IF NOT EXISTS `dis`.`korisnik_rola` (
  `ID_ROLA` INT(11) NOT NULL AUTO_INCREMENT,
  `NAZIV` VARCHAR(45) NOT NULL,
  `OPIS` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ROLA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dis`.`korisnik_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dis`.`korisnik_status` ;

CREATE TABLE IF NOT EXISTS `dis`.`korisnik_status` (
  `ID_STATUS` INT(11) NOT NULL AUTO_INCREMENT,
  `NAZIV` VARCHAR(45) NOT NULL,
  `OPIS` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_STATUS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dis`.`korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dis`.`korisnik` ;

CREATE TABLE IF NOT EXISTS `dis`.`korisnik` (
  `ID_KORISNIK` INT(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(40) NOT NULL,
  `EMAIL` VARCHAR(30) NOT NULL,
  `POSLEDNJE_LOGOVANJE` VARCHAR(45) NULL DEFAULT NULL,
  `ID_ROLA` INT(11) NOT NULL,
  `ID_STATUS` INT(11) NOT NULL,
  PRIMARY KEY (`ID_KORISNIK`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC) ,
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) ,
  INDEX `fk_korisnik_korisnik_rola_idx` (`ID_ROLA` ASC) ,
  INDEX `fk_korisnik_korisnik_status1_idx` (`ID_STATUS` ASC) ,
  CONSTRAINT `fk_korisnik_korisnik_rola`
    FOREIGN KEY (`ID_ROLA`)
    REFERENCES `dis`.`korisnik_rola` (`ID_ROLA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_korisnik_status1`
    FOREIGN KEY (`ID_STATUS`)
    REFERENCES `dis`.`korisnik_status` (`ID_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dis`.`email_verifikacija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dis`.`email_verifikacija` ;

CREATE TABLE IF NOT EXISTS `dis`.`email_verifikacija` (
  `ID_EMAIL_VERIFIKACIJA` INT(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(30) NOT NULL,
  `VERIFIKACIONI_KOD` INT(11) NOT NULL,
  `VREME_SLANJA_KODA` DATETIME NULL DEFAULT NULL,
  `VREME_REGISTRACIJE` DATETIME NULL DEFAULT NULL,
  `ID_KORISNIK` INT(11) NOT NULL,
  `ID_STATUS` INT(11) NOT NULL,
  PRIMARY KEY (`ID_EMAIL_VERIFIKACIJA`),
  INDEX `fk_email_verifikacija_korisnik1_idx` (`ID_KORISNIK` ASC) ,
  INDEX `fk_email_verifikacija_email_verifikacija_status1_idx` (`ID_STATUS` ASC) ,
  CONSTRAINT `fk_email_verifikacija_email_verifikacija_status1`
    FOREIGN KEY (`ID_STATUS`)
    REFERENCES `dis`.`email_verifikacija_status` (`ID_EMAIL_VERIFIKACIJA_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_verifikacija_korisnik1`
    FOREIGN KEY (`ID_KORISNIK`)
    REFERENCES `dis`.`korisnik` (`ID_KORISNIK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
